<#
.SYNOPSIS
    Register a Windows logon-time autostart so viz_gui2.py runs at user logon
    (port 9000, no console window). After install, every boot/logon you can
    just open http://127.0.0.1:9000/ — no manual start needed.

    NOTE: this targets viz_gui2.py (seeds 2.0, categorized & collapsible).
    The legacy viz_gui.py is no longer autostarted.

.PARAMETER Port
    HTTP port (default 9000).

.PARAMETER PythonExe
    Path to pythonw.exe (preferred — no flashing console). If empty, auto-resolved
    from the python.exe on PATH.

.PARAMETER Uninstall
    Remove the scheduled task instead of installing it.

.PARAMETER Now
    Also kick off the task immediately after installing.

.EXAMPLES
    pwsh tools\install_autostart.ps1 -Now
    pwsh tools\install_autostart.ps1 -PythonExe "E:\--IDLE\pythonw.exe" -Now
    pwsh tools\install_autostart.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [int]$Port = 9000,
    [string]$PythonExe = "",
    [switch]$Uninstall,
    [switch]$Now
)

$ErrorActionPreference = "Stop"
$TaskName = "MJFuzzVizGUI2"
$LegacyTaskName = "MJFuzzVizGUI"

# Project root = parent of this tools/ folder.
$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$VizScript   = Join-Path $ProjectRoot "tools\viz_gui2.py"
$LauncherVbs = Join-Path $ProjectRoot "tools\autostart_launcher.vbs"
$LauncherIni = Join-Path $ProjectRoot "tools\autostart_launcher.ini"
$LogDir      = Join-Path $ProjectRoot ".cache"
$LogFile     = Join-Path $LogDir "viz_gui2.log"


if (-not (Test-Path $VizScript)) {
    throw "viz_gui2.py not found: $VizScript"
}
if (-not (Test-Path $LauncherVbs)) {
    throw "autostart_launcher.vbs not found: $LauncherVbs (regenerate from repo)"
}

# Resolve interpreter. We DON'T require pythonw.exe — the .vbs launcher
# spawns python.exe with intWindowStyle=0 so no console window appears.
if (-not $PythonExe) {
    $py = Get-Command python.exe -ErrorAction SilentlyContinue
    if (-not $py) {
        throw "python.exe not on PATH; pass -PythonExe explicitly."
    }
    $PythonExe = $py.Path
    # Prefer pythonw.exe if it actually exists alongside (slightly cleaner).
    $candidate = Join-Path (Split-Path $py.Path) "pythonw.exe"
    if (Test-Path $candidate) { $PythonExe = $candidate }
}
if (-not (Test-Path $PythonExe)) {
    throw "Python interpreter not found: $PythonExe"
}

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# The Run entry invokes wscript.exe (built-in, on PATH) on the .vbs launcher,
# which itself spawns python.exe with NO console window. Closing nothing —
# wscript exits immediately after Run() returns; the python process keeps living.
$WScriptExe = Join-Path $env:WINDIR "System32\wscript.exe"
$CmdLine    = "`"$WScriptExe`" `"$LauncherVbs`""

# Use HKCU Run registry key — no admin rights required, current user only.
# Task Scheduler alternatives (Register-ScheduledTask) require elevation on PS 5.1.
$RunKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"

if ($Uninstall) {
    if (Get-ItemProperty -Path $RunKey -Name $TaskName -ErrorAction SilentlyContinue) {
        Remove-ItemProperty -Path $RunKey -Name $TaskName
        Write-Host "[ok] removed autostart entry '$TaskName' from registry Run key"
    } else {
        Write-Host "[noop] '$TaskName' not found in registry Run key"
    }
    if (Get-ItemProperty -Path $RunKey -Name $LegacyTaskName -ErrorAction SilentlyContinue) {
        Remove-ItemProperty -Path $RunKey -Name $LegacyTaskName
        Write-Host "[ok] also removed legacy autostart entry '$LegacyTaskName'"
    }
    # Also kill any running instance
    Get-Process -Name "python" -ErrorAction SilentlyContinue |
        Where-Object { $_.MainWindowTitle -eq "" } | ForEach-Object { $_.Kill() }
    return
}

# Always remove the legacy viz_gui.py autostart (user requested gui1 no longer auto-starts).
if (Get-ItemProperty -Path $RunKey -Name $LegacyTaskName -ErrorAction SilentlyContinue) {
    Remove-ItemProperty -Path $RunKey -Name $LegacyTaskName
    Write-Host "[ok] removed legacy viz_gui.py autostart entry '$LegacyTaskName'"
}

# Write (or overwrite) the .ini consumed by autostart_launcher.vbs
# (so we don't have to regenerate the .vbs every install).
$IniText = "; auto-generated by install_autostart.ps1 -- edit via that script`r`n" +
           "python = $PythonExe`r`n" +
           "port = $Port`r`n"
Set-Content -Path $LauncherIni -Value $IniText -Encoding ASCII
Write-Host "[ok] wrote launcher config: $LauncherIni"

# Write (or overwrite) the Run entry
Set-ItemProperty -Path $RunKey -Name $TaskName -Value $CmdLine
Write-Host "[ok] registered autostart: HKCU\...\Run\$TaskName"
Write-Host "     launcher    : $LauncherVbs (hidden, via wscript.exe)"
Write-Host "     interpreter : $PythonExe"
Write-Host "     script      : $VizScript"
Write-Host "     port        : $Port"
Write-Host "     workdir     : $ProjectRoot"
Write-Host "     trigger     : at user logon (registry Run key, no console window)"
Write-Host ""

if ($Now) {
    # Kill any stale viz_gui2 process so we cleanly start the new one.
    Get-CimInstance Win32_Process -Filter "Name='python.exe'" -ErrorAction SilentlyContinue |
        Where-Object { $_.CommandLine -like '*viz_gui2*' } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }

    # Launch via the same .vbs the registry uses, so this matches the boot path.
    Start-Process -FilePath $WScriptExe -ArgumentList "`"$LauncherVbs`"" -WindowStyle Hidden | Out-Null

    Write-Host "[..] viz_gui2 launched in background (hidden), waiting for port $Port ..."
    $deadline = (Get-Date).AddSeconds(8)
    $ok = $false
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Milliseconds 600
        try {
            $r = [System.Net.Sockets.TcpClient]::new("127.0.0.1", $Port)
            $r.Close(); $ok = $true; break
        } catch {}
    }
    if ($ok) {
        Write-Host "[ok] viz_gui2 is listening at http://127.0.0.1:$Port/  (no console window)"
    } else {
        Write-Host "[warn] port $Port not responding yet -- check log:"
        Write-Host "       $LogFile"
        Write-Host "       or run foreground:  cd `"$ProjectRoot`"; & `"$PythonExe`" tools\viz_gui2.py"
    }
}

Write-Host ""
Write-Host "Manage:"
Write-Host "  Check  : Get-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' $TaskName"
Write-Host "  Remove : powershell -File $PSCommandPath -Uninstall"
